version: '3.9'
services:
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - "backend"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "raccoman@student.42roma.it"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    networks:
      - "backend"

  nextjs:
    build: nextjs/
    container_name: nextjs
    restart: always
    ports:
      - ${NEXTJS_PORT}:${NEXTJS_PORT}
    environment:
      PORT: ${NEXTJS_PORT}
    networks:
      - "frontend"

networks:
  frontend:
  backend: