version: '3.9'
services:
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - "backend"

  hasura:
    image: hasura/graphql-engine:v2.8.0.cli-migrations-v3
    container_name: hasura
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, query-log
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "${JWT_SECRET}", "header": {"type": "Cookie", "name": "${JWT_COOKIE_NAME}" }}'
    volumes:
      - "./hasura/migrations:/hasura-migrations"
      - "./hasura/metadata:/hasura-metadata"
    networks:
      - "backend"

  nextjs:
    build: nextjs/
    container_name: nextjs
    restart: always
    ports:
      - ${NEXTJS_PORT}:${NEXTJS_PORT}
    environment:
      PORT: ${NEXTJS_PORT}
    networks:
      - "frontend"

networks:
  frontend:
  backend:
  