version: '3.9'
services:
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - "backend"

  hasura:
    image: hasura/graphql-engine:v2.8.0.cli-migrations-v3
    container_name: hasura
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
    volumes:
      - "hasura_metadata:/hasura-metadata"
      - "hasura_migrations:/hasura-migrations"
    networks:
      - "backend"

  # backend:
  #   ports:
  #      - "${BACKEND_PORT}:${BACKEND_PORT}"
  #   restart: always
  #   build: ./backend
  #   container_name: backend
  #   depends_on:
  #     - postgres
  #   environment:
  #     - DB_USER=${DB_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_NAME=${DB_NAME}
  #     - DB_HOST=postgres
  #   volumes:
  #     - "./backend:/usr/src/backend"
  #   networks:
  #     - trans-net

  nextjs:
    build: nextjs/
    container_name: nextjs
    restart: always
    ports:
      - "3000:3000"
      - "80:80"
    networks:
      - "frontend"

volumes:
  hasura_metadata:
    driver_opts:
      type: none
      device: ${PWD}/hasura/metadata
      o: bind
  hasura_migrations:
    driver_opts:
      type: none
      device: ${PWD}/hasura/migrations
      o: bind

networks:
  frontend:
  backend:
  