version: '3.9'
services:
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - "backend"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend

  nextjs:
    build: nextjs/
    container_name: nextjs
    restart: always
    ports:
      - ${NEXTJS_PORT}:${NEXTJS_PORT}
    environment:
      PORT: ${NEXTJS_PORT}
    networks:
      - frontend

networks:
  frontend:
  backend: